name: Generate PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:latest
        with:
          args: "exercises/IntensivAufgaben.md -f markdown-implicit_figures -o IntensivAufgaben.pdf" # gets appended to pandoc command

      - uses: actions/upload-artifact@v4
        with:
          name: IntensivAufgaben
          path: IntensivAufgaben.pdf
