name: Generate PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/latex:latest
        with:
          args: "exercises/IntensivExercises.md -f markdown-implicit_figures -o exercises/IntensivExercises.pdf" # gets appended to pandoc command
