name: Generate PDF

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:latest
        with:
          args: "exercises/IntensivAufgaben.md -f markdown-implicit_figures -o public/index.html" # gets appended to pandoc command
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
